default: &default
  adapter: postgresql
  encoding: unicode
  pool: 2
  username: postgres
  password: password
  host: localhost

development:
  <<: *default
  database: spoilerbot_development

production:
  <<: *default
  database: spoilerbot_production
